### PR TITLE
SD Data-logging Fix- V3.1.4

### PR DESCRIPTION
**Pull request by IoaSman1**
- Fixed SD Card  Logging Issue 1:  Data-logging Duration
- Fixed SD Card  Logging Issue 2:  Data stream to OpenBCI GUI hangs after closing Data file

### CODE REVIEW

**Comment by zeyus** [comment]
Thanks for this, I'm in the process of testing this at the moment, the code looks good, I'm just wondering if it wouldn't make sense to also include a check for the current sample rate so the block allocation varies depending on the sample rate, e.g.:

```{arduino}
// SD_Card_Stuff.ino

// ...
boolean setupSDcard(char limit){
  // ...
  BLOCK_COUNT = ceil(BLOCK_COUNT / 250 * board.getSampleRate().toInt());
}
// ...
```

That way if you use 1000Hz, you'll get a larger file...also this setting shouldn't affect performance as it only happens once during the SD card setup.

**Comment by zeyus** [comment]
Thanks for this, I'm in the process of testing this at the moment, the code looks good, I'm just wondering if it wouldn't make sense to also include a check for the current sample rate so the block allocation varies depending on the sample rate, e.g.:

```{arduino}
// SD_Card_Stuff.ino

// ...
boolean setupSDcard(char limit){
  // ...
  BLOCK_COUNT = ceil(BLOCK_COUNT / 250 * board.getSampleRate().toInt());
}
// ...
```

That way if you use 1000Hz, you'll get a larger file...also this setting shouldn't affect performance as it only happens once during the SD card setup.

**Review by zeyus — APPROVED** [review]
Looks good to me, I've also tested these changes and nothing broke (not that I expected it), although I haven't overrun the SD file length yet, but I guess I can try that from the GUI.

**Review by evaesteban — APPROVED** [review]

**Comment by zeyus** [comment]
I've just noticed that if the data overruns the file there's no footer written to the sdcard (I'll need to have another look but I'm guessing the limit for writing data should be `reserved size - footer length`

**Comment by IoaSman1** [comment]
One more fixed is included
- Fixed - ADS1299 Data Acquisition and Data Streaming on Hardware Side was staying ON even after stop streaming session

**Comment by retiutut** [comment]
+1 from https://openbci.com/forum/index.php?p=/discussion/3916/uneven-results-with-sd-card-files&

**Review by retiutut — APPROVED** [review]

**Pull request merged**
